/**
 * Every XDS product and its Product ID, from "Products and IDs Updated.xlsx" (259 products).
 * Clients choose their products during onboarding; the API pages only need the IDs.
 */
export const PRODUCT_CATALOGUE: [id: number, name: string][] = [
  [1, "Consumer Authentication"],
  [2, "Consumer Trace"],
  [3, "Consumer Address Trace"],
  [4, "Consumer Telephone Trace"],
  [5, "Consumer Account Trace"],
  [6, "Multiple Consumer Trace"],
  [7, "Consumer Easy Trace"],
  [8, "Consumer Pre-Screen Trace"],
  [9, "Identity Verification Trace"],
  [12, "Business Enquiry"],
  [14, "Director Enquiry"],
  [15, "Consumer Credit Enquiry"],
  [19, "Consumer Trace Web Service"],
  [20, "Consumer Address Trace Web Service"],
  [21, "Consumer Telephone Trace Web Service"],
  [22, "Consumer Account Trace Web Service"],
  [23, "Consumer Easy Trace Web Service"],
  [24, "Consumer Identity Verification Web Service"],
  [25, "Business Enquiry Web Service"],
  [26, "Director Enquiry Web Service"],
  [27, "Consumer Credit Enquiry Web Service"],
  [28, "Consumer Application Credit Enquiry Web Service"],
  [31, "Consumer Credit Application"],
  [32, "Consumer Trace Confirmed Information"],
  [33, "Judgement Enquiry"],
  [34, "Default Enquiry"],
  [35, "Admin Order Enquiry"],
  [36, "Sequestration Enquiry"],
  [37, "Full public Domain Enquiry"],
  [38, "Debt Review Enquiry"],
  [39, "Marital Enquiry Trace"],
  [40, "Business Standard Online Enquiry"],
  [41, "Business Detailed Online Enquiry"],
  [42, "Deeds Enquiry"],
  [43, "Business Investigative Enquiry"],
  [44, "Bank Codes Enquiry"],
  [45, "Account Verification"],
  [46, "Verify ID Number Enquiry"],
  [47, "Profile ID Number Enquiry"],
  [48, "Individual File Enquiry"],
  [49, "Request Birth Certificate"],
  [50, "Request Death Certificate"],
  [51, "CellC Scoring"],
  [52, "Standard Bank Bureau Data"],
  [53, "Consumer Default Alert Listings"],
  [54, "Commercial Default Alert Listings"],
  [55, "SMS - Notification"],
  [56, "SMS - DefaultAlert"],
  [59, "NLR Registrations"],
  [60, "NLR Closures"],
  [61, "Cell C Score Card"],
  [68, "MTN Score Card"],
  [69, "CIPC Plus"],
  [75, "SMS - OTP"],
  [78, "BLDSCustomVetting"],
  [79, "Credit4LifeSMSAlert"],
  [80, "Collections Early Stage Snapshot"],
  [81, "Collections Late Stage Snapshot"],
  [83, "MPOWA Custom Vetting"],
  [84, "Account verification SureTransact"],
  [87, "ACFE Risk Report"],
  [88, "Waco Low Risk"],
  [89, "Waco Medium Risk"],
  [90, "Business Adverse"],
  [91, "KYC"],
  [92, "BridgeLoans Custom Vetting"],
  [93, "ACPAS Custom Vetting"],
  [94, "Consumer i-Check"],
  [95, "Score Indicator"],
  [99, "Incline Custom Vetting"],
  [100, "Account Verification Real Time"],
  [101, "ID Photo Verification"],
  [102, "Qualification Verification"],
  [103, "Linkage Detector"],
  [104, "Motor Vehicle Verification"],
  [105, "TWPOS"],
  [107, "ConsumerCreditScore- Finance27"],
  [108, "ConsumerCreditScore-Babereki"],
  [109, "ConsumerPrevet-MFin"],
  [110, "Vodacom Canvassing"],
  [121, "ConsumerPrevet-GloCell"],
  [122, "EZ4U Loans Custom Vetting"],
  [123, "XDS Quick Custom Vetting"],
  [124, "JD Customvetting"],
  [125, "XDS LMS CustomVetting"],
  [126, "Idividual Deeds Enquiry"],
  [127, "Identity Verification Plus"],
  [128, "MicroLoans Snapshot"],
  [129, "DaPulseScore"],
  [130, "E4AddressReport"],
  [131, "Contact Details"],
  [132, "Consumer Summary Credit Application"],
  [133, "BLDS Customvetting"],
  [134, "LinkageSearch"],
  [135, "LinkageSearchReport"],
  [136, "LinkageDetectorReport"],
  [137, "MTN Customvetting"],
  [138, "MTN Commercial Customvetting"],
  [139, "ID BioMetric verification"],
  [140, "Commercial Questionnaire"],
  [142, "Payment Gap"],
  [145, "Consumer Affordability"],
  [146, "JD Mobi Process"],
  [147, "Batch Credit Enquiry"],
  [148, "DIA ID BioMetric verification"],
  [149, "Face View"],
  [152, "KYC Online"],
  [153, "Realtime IDV"],
  [154, "Realtime Marital Enquiry"],
  [155, "Realtime IDV and Marital Enquiry"],
  [156, "Business Status Enquiry"],
  [157, "Public Disclosure Enquiry"],
  [158, "Biometric Verification with Contact Information"],
  [159, "Biometric Verification with Affordability"],
  [160, "Biometric Verification with Presage Score"],
  [161, "Biometrics With Contact and Affordability"],
  [162, "Biometrics With Contact and Presage Score"],
  [163, "Biometrics With Affordability and Presage Score"],
  [164, "Biometrics With Contact,Affordability and Presage"],
  [165, "RewardsCo-MTN"],
  [166, "Fraud Management Platform-FMP"],
  [167, "ID BioMetric verification without photo"],
  [168, "ID Facial verification"],
  [169, "Credit Score Simulator"],
  [170, "ID Facial BioMetric verification"],
  [171, "ID Facial Realtime ID Verification"],
  [172, "MTrace Lite"],
  [175, "Signed NDA"],
  [176, "XDS Compliance Exposure Consumer"],
  [177, "XDS Compliance Exposure Commercial"],
  [178, "XDS ID Verification"],
  [179, "ID BioMetric verification without watermark"],
  [181, "Bank Statement"],
  [182, "Realtime IDV Custom 9"],
  [184, "Rental Genie Custom Vetting"],
  [185, "MTN Canvassing"],
  [186, "MFDOVS"],
  [187, "Realtime IDV with ID Dates"],
  [189, "MFDOVS SMS"],
  [190, "MFDOVS Facial Verification"],
  [191, "Consumer Address Information"],
  [192, "Consumer Deeds Linkage Enquiry"],
  [193, "Commercial Deeds Linkage Enquiry"],
  [194, "DOVS"],
  [195, "Account Verification Real Time Plus"],
  [196, "Digital Consumer Verification"],
  [197, "Digital Address Verification"],
  [198, "Digital Contact Verification"],
  [199, "Bank Codes Enquiry Plus"],
  [200, "Geo location Verification"],
  [201, "Consent Engine"],
  [202, "AVS Plus with Realtime IDV"],
  [203, "Consumer Score"],
  [204, "Consumer Employment"],
  [205, "Consumer Telephone"],
  [206, "Income V1"],
  [207, "Bureau Expenses"],
  [208, "Sim Swap"],
  [209, "Commercial Score"],
  [210, "TelecoBatch_digitial"],
  [212, "KYC + Realtime IDV"],
  [213, "KYC + Principal Link"],
  [214, "KYC + Deeds"],
  [215, "KYC + SAFPS"],
  [216, "KYC + Fraud"],
  [217, "KYC + IdentityImage"],
  [218, "KYC + Compliance Exposure"],
  [220, "MTN SME Canvassing"],
  [221, "Cash Converters Enquiry"],
  [222, "CustomVettingY"],
  [223, "Consumer Demographic Information"],
  [224, "Arrear Amount"],
  [226, "Ikhaya Vetting"],
  [227, "Commercial DOVS"],
  [228, "Thin File Scoring"],
  [229, "POPIA Consumer report"],
  [230, "POPIA Commercial report"],
  [231, "Consumer Judgment Enquiry"],
  [233, "XDS Compliance Exposure Consumer Lite"],
  [234, "Faceview Plus"],
  [235, "XDS-PreCheck"],
  [236, "ID BioMetric Verification Non-NPR"],
  [237, "Realtime IDV and Marital Enquiry Non-NPR"],
  [239, "RealTime IDV Lineage"],
  [240, "Realtime IDV and Photo Verification"],
  [241, "DataNamix KYC"],
  [242, "Consumer Authentication V2.3"],
  [243, "XDS Compliance Exposure Consumer - OFAC"],
  [244, "Cash Converters Enquiry V4"],
  [245, "XDS Compliance Exposure Consumer Lite - OFAC"],
  [246, "Credit EnquiryP V5"],
  [247, "Multi-Factor Authentication"],
  [248, "Ignition Telco Vetting"],
  [249, "XDS Compliance Exposure Consumer Standard"],
  [250, "XDS Compliance Exposure Commercial Standard"],
  [251, "Custom KYC"],
  [252, "iTalk Vetting"],
  [253, "Qualification Enquiry"],
  [254, "Faceview Plus - with full failover"],
  [256, "Name Validation"],
  [257, "Agility cellc vetting"],
  [261, "Custom Realtime IDV PDF"],
  [262, "Prevet"],
  [263, "Kyc 2 Year"],
  [264, "Kyc 10 Year"],
  [265, "Faceview Plus - with full failover V2"],
  [266, "Full Snapshot IDV"],
  [267, "Credit Enquiry Report V5"],
  [268, "Credit Enquiry log"],
  [316, "Credit Enquiry Report V6"],
  [318, "Full Snapshot Face View"],
  [319, "iTalk Vetting_v1"],
  [320, "Consumer Financial Data"],
  [321, "Commercial Trust"],
  [322, "One month Loan"],
  [323, "Business Quick Vet"],
  [324, "ID BioMetric Verification V2"],
  [325, "ID BioMetric Verification Report V2 (Fingerprint)"],
  [326, "Name Check"],
  [327, "Name Check (Bureau)"],
  [328, "Identity Status Check"],
  [329, "Identity Status Check (Bureau)"],
  [330, "Real Time Identity Status Check"],
  [331, "Real Time Identity Status Check (DHA)"],
  [332, "Identity Verification"],
  [333, "Identity Verification (Bureau)"],
  [334, "Real Time Identity Verification"],
  [335, "Real Time Identity Verification (DHA)"],
  [336, "Face Verification"],
  [337, "Face Verification (Bureau)"],
  [338, "Real Time Face Verification"],
  [339, "Real Time Face Verification (DHA)"],
  [344, "Commercial Detailed Modular Report"],
  [346, "Business Detailed Online Enquiry With Turnover"],
  [348, "Vehicle Search by ID Enquiry"],
  [349, "Driver Licence Enquiry"],
  [350, "Face Verification with Contact"],
  [351, "Face Verification with Contact (Bureau)"],
  [352, "Real Time Face Verification with Contact"],
  [353, "Real Time Face Verification with Contact (DHA)"],
  [354, "Identity Lineage"],
  [1148, "Custom Realtime IDV PDF DHA"],
  [1149, "DOVS DHA"],
  [1150, "FaceView DHA"],
  [1151, "FaceView Plus DHA"],
  [1152, "Faceview Plus - with full failover DHA"],
  [1153, "ID Facial verification DHA"],
  [1154, "Realtime IDV and Photo Verification DHA"],
  [1155, "Realtime IDV DHA"],
  [1156, "Realtime IDV and Marital Enquiry DHA"],
  [1157, "RealTime IDV Lineage DHA"],
  [1158, "Realtime Marital Enquiry DHA"],
  [1159, "XDS Compliance Exposure Consumer DHA"],
  [1160, "XDS Compliance Exposure Consumer Lite DHA"],
  [1161, "XDS-PreCheck DHA"],
  [1162, "Realtime IDV Custom 9 DHA"],
  [1163, "Faceview Plus - with full failover V2 DHA"],
  [1164, "Full Snapshot Face View DHA"],
  [1165, "Full Snapshot IDV DHA"],
];

export function productName(id: number) {
  return PRODUCT_CATALOGUE.find(([pid]) => pid === id)?.[1];
}
